# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20db9fee04d5d57f69e116638dadc5bfc3043a61b5935d6e80dc62410753da4d101c7d3f45f1d69eae44a15f86eaa8ffa1971d374df71e86ae724a007cd10063

test:
  secret_key_base: 713c89f2d36e8df7086e7e6e48a80e09c0038abfd6bf0c00fdc343de17a00b64172a634317f79f6cd26272836dbe61efa7073d97e636146cdee31369b80fc957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
